import { useState } from "react";
import Layout from "../components/Layout";
import SEO from "../components/SEO";
import {
  ShieldCheck, Pulse, Globe, Sparkle, Users, Lightning,
  CaretDown, CaretUp, Virus, Heartbeat, ChartLineUp,
} from "@phosphor-icons/react";

const STATS = [
  { label: "Verified sources", value: "16+", icon: ShieldCheck },
  { label: "Countries tracked", value: "16", icon: Globe },
  { label: "Refresh interval", value: "15min", icon: Pulse },
  { label: "AI-powered briefings", value: "Live", icon: Sparkle },
];

const TIMELINE = [
  { date: "Q1 2026", title: "Platform launch", body: "Global Hanta Map goes live with 16-country surveillance, AI briefings, and an editorial workflow." },
  { date: "Q2 2026", title: "Real-time RSS scrapers", body: "Automated 15-minute polling of WHO, CDC, PAHO, ECDC and national ministries deployed." },
  { date: "Q3 2026", title: "Public API beta", body: "Researcher / journalist API with API-key authentication and rate-limited access (planned)." },
  { date: "Q4 2026", title: "Multi-disease expansion", body: "Architecture extended beyond Hantavirus to Dengue, Ebola, Nipah, Avian flu and Measles (planned)." },
];

const FAQ = [
  { q: "Where does your data come from?", a: "Exclusively from official public health authorities — WHO, CDC, ECDC, PAHO, and national ministries of health. Every record links back to its source bulletin." },
  { q: "How often is data updated?", a: "Our automated collectors poll source feeds every 15 minutes. Country pages display the timestamp of the most recent update." },
  { q: "Why do figures differ from a national bulletin?", a: "National bulletins may publish weekly while we update continuously, and bulletins are sometimes revised retrospectively. We always link to the source so you can compare." },
  { q: "Are the AI summaries reliable?", a: "AI summaries are generated by Claude Sonnet 4.5 from the verified figures we provide. The model never invents numbers or sources, and AI-generated text is clearly labelled." },
  { q: "Is this medical advice?", a: "No. Global Hanta Map is informational and does not replace professional medical advice. Consult your doctor or local public health authority for guidance." },
  { q: "How is the platform funded?", a: "Display advertising via Google AdSense. We do not accept paid placements that influence editorial content." },
];

const PARTNERS = ["WHO", "CDC", "ECDC", "PAHO", "MINSAL", "RKI", "KDCA", "MoH"];

export default function About() {
  const [openFaq, setOpenFaq] = useState(0);

  return (
    <Layout>
      <SEO
        title="About & Mission"
        description="Global Hanta Map's mission, methodology, technology stack, partner sources, and roadmap for global Hantavirus surveillance."
        path="/about"
      />
      {/* Hero */}
      <section className="border-b border-ink-3">
        <div className="max-w-[1100px] mx-auto px-4 md:px-8 py-16">
          <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-3">
            About · Mission · Methodology
          </div>
          <h1 className="font-display font-black text-4xl md:text-6xl tracking-tight leading-[0.95]">
            Public health surveillance,
            <br />
            <span className="text-signal-red">in the public interest.</span>
          </h1>
          <p className="text-zinc-300 leading-relaxed text-lg mt-6 max-w-3xl">
            Global Hanta Map is an independent disease surveillance platform that
            aggregates verified Hantavirus outbreak intelligence in real time.
            We exist because timely, source-linked outbreak data should be
            accessible to everyone — clinicians, journalists, researchers, and
            the public alike.
          </p>
        </div>
      </section>

      {/* Stats */}
      <section className="max-w-[1100px] mx-auto px-4 md:px-8 py-10 grid grid-cols-2 md:grid-cols-4 gap-3">
        {STATS.map(({ label, value, icon: Icon }) => (
          <div key={label} data-testid="about-stat" className="border border-ink-3 bg-ink-1 p-5">
            <Icon size={22} weight="duotone" className="text-signal-red mb-3" />
            <div className="font-display font-black text-3xl">{value}</div>
            <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mt-1">
              {label}
            </div>
          </div>
        ))}
      </section>

      {/* Mission pillars */}
      <section className="max-w-[1100px] mx-auto px-4 md:px-8 py-10">
        <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-2">
          Mission
        </div>
        <h2 className="font-display font-black text-3xl md:text-4xl tracking-tight mb-8">
          Why outbreak monitoring matters.
        </h2>
        <div className="grid md:grid-cols-3 gap-4">
          {[
            { icon: Virus, title: "Detect early", body: "Hantaviruses (Andes, Sin Nombre, Seoul, Puumala…) emerge from rodent reservoirs in rural and peri-urban areas. Early detection saves lives." },
            { icon: Heartbeat, title: "Inform clinicians", body: "Timely outbreak intelligence helps emergency departments and public health officers triage suspected HPS / HFRS cases." },
            { icon: ChartLineUp, title: "Power research", body: "Open, structured outbreak data underpins phylogenetics, vaccine development, and zoonotic-spillover studies." },
          ].map(({ icon: Icon, title, body }) => (
            <div key={title} className="border border-ink-3 bg-ink-1 p-6">
              <Icon size={28} weight="duotone" className="text-signal-red mb-4" />
              <div className="font-display font-bold text-lg mb-2">{title}</div>
              <p className="text-sm text-zinc-400 leading-relaxed">{body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Methodology */}
      <section className="max-w-[1100px] mx-auto px-4 md:px-8 py-10 grid lg:grid-cols-2 gap-8">
        <div>
          <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-2">
            Methodology
          </div>
          <h2 className="font-display font-black text-3xl tracking-tight mb-3">
            How we verify every record.
          </h2>
          <p className="text-zinc-300 leading-relaxed mb-3">
            Detect → match to source → score authority → deduplicate → AI
            summarize → editor review → publish. Every statistic is anchored to
            an accredited source bulletin, and high-severity records require a
            second editor sign-off.
          </p>
          <p className="text-zinc-400 text-sm">
            Read the full workflow on our{" "}
            <a href="/transparency" className="text-signal-blue underline">
              Transparency page
            </a>.
          </p>
        </div>
        <div>
          <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-2">
            Technology stack
          </div>
          <h2 className="font-display font-black text-3xl tracking-tight mb-3">
            Modern, open, auditable.
          </h2>
          <ul className="text-zinc-300 space-y-1 text-sm">
            <li>• <strong>React</strong> + <strong>Tailwind</strong> — fast, accessible UI.</li>
            <li>• <strong>Leaflet</strong> + CartoDB Dark Matter — open-source mapping.</li>
            <li>• <strong>FastAPI</strong> + <strong>MongoDB</strong> — async backend.</li>
            <li>• <strong>APScheduler</strong> — 15-min cron polling.</li>
            <li>• <strong>Claude Sonnet 4.5</strong> — neutral AI briefings.</li>
            <li>• <strong>Resend</strong> — transactional email alerts.</li>
          </ul>
        </div>
      </section>

      {/* Timeline */}
      <section className="border-y border-ink-3 bg-ink-1 py-14">
        <div className="max-w-[1100px] mx-auto px-4 md:px-8">
          <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-2">
            Roadmap
          </div>
          <h2 className="font-display font-black text-3xl md:text-4xl tracking-tight mb-8">
            Project evolution
          </h2>
          <ol className="relative border-l border-signal-red/40 ml-3 space-y-8">
            {TIMELINE.map((t) => (
              <li key={t.date} data-testid="timeline-item" className="ml-6">
                <span className="absolute -left-[7px] mt-1.5 w-3 h-3 rounded-full bg-signal-red ring-4 ring-ink-1" />
                <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-signal-red mb-1">
                  {t.date}
                </div>
                <div className="font-display font-bold text-lg text-white">{t.title}</div>
                <p className="text-sm text-zinc-400 leading-relaxed mt-1">{t.body}</p>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* Partners */}
      <section className="max-w-[1100px] mx-auto px-4 md:px-8 py-12">
        <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-3">
          Trusted data sources
        </div>
        <div className="flex flex-wrap items-center gap-x-10 gap-y-3">
          {PARTNERS.map((s) => (
            <span
              key={s}
              className="font-display font-black text-2xl tracking-tighter text-zinc-300 hover:text-white transition-colors"
            >
              {s}
            </span>
          ))}
        </div>
      </section>

      {/* Team */}
      <section className="max-w-[1100px] mx-auto px-4 md:px-8 py-10">
        <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-2">
          Team
        </div>
        <h2 className="font-display font-black text-3xl tracking-tight mb-6">
          Editorial & engineering
        </h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {[
            { role: "Editor in Chief", body: "Coordinates verification workflow and source partnerships." },
            { role: "Surveillance Lead", body: "Manages scraper feeds, dedup logic, and authority scoring." },
            { role: "Data Engineer", body: "Owns the data pipeline, scheduler, and API surface." },
          ].map(({ role, body }) => (
            <div key={role} className="border border-ink-3 bg-ink-1 p-5">
              <div className="w-10 h-10 rounded-sm bg-signal-red/20 grid place-items-center mb-3">
                <Users size={20} weight="duotone" className="text-signal-red" />
              </div>
              <div className="font-display font-bold mb-1">{role}</div>
              <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-2">
                Open · 2026
              </div>
              <p className="text-sm text-zinc-400">{body}</p>
            </div>
          ))}
        </div>
        <p className="text-xs text-zinc-500 mt-4">
          Interested in joining? Email <a className="text-signal-blue underline" href="mailto:info@globalhantamap.com">info@globalhantamap.com</a>.
        </p>
      </section>

      {/* FAQ */}
      <section className="border-t border-ink-3 bg-ink-1 py-14">
        <div className="max-w-[820px] mx-auto px-4 md:px-8">
          <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-zinc-500 mb-2">
            FAQ
          </div>
          <h2 className="font-display font-black text-3xl tracking-tight mb-6">
            Frequently asked
          </h2>
          <div className="border border-ink-3 bg-ink-0">
            {FAQ.map((f, i) => (
              <div key={f.q} className="border-b border-ink-3 last:border-b-0">
                <button
                  data-testid={`faq-toggle-${i}`}
                  onClick={() => setOpenFaq(openFaq === i ? -1 : i)}
                  className="w-full text-left px-5 py-4 flex items-center justify-between gap-4 hover:bg-ink-2"
                >
                  <span className="font-display font-bold text-base">{f.q}</span>
                  {openFaq === i ? <CaretUp size={18} /> : <CaretDown size={18} />}
                </button>
                {openFaq === i && (
                  <div className="px-5 pb-5 text-zinc-300 text-sm leading-relaxed">
                    {f.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </Layout>
  );
}
