import LegalPage from "../components/LegalPage";

export default function Disclaimer() {
  return (
    <LegalPage
      kicker="Legal"
      title="Disclaimer"
      path="/disclaimer"
      description="Important notices about the limitations of Global Hanta Map's published data, accuracy, and source verification."
      intro='This platform aggregates publicly available health data from official government and public health organizations and is not intended to replace professional medical advice, diagnosis, or treatment.'
      sections={[
        { heading: "Accuracy limitations", body: "While we strive for the highest standard of accuracy, Hantavirus surveillance data evolves continually as new cases are confirmed, reclassified, or removed. The figures shown on this Service may differ from official bulletins published moments before, and we cannot guarantee that every record is current at the second of viewing." },
        { heading: "Data delays", body: "Our automated collectors poll official sources approximately every 15 minutes. National ministries of health may publish weekly bulletins, while WHO Disease Outbreak News is irregular. Expect delays of minutes to several days between an official announcement and its appearance on Global Hanta Map." },
        { heading: "Source verification notice", body: "Every statistic on this Service is linked to at least one official source. Where multiple sources publish conflicting numbers we display the source with the strongest accreditation (WHO > national ministry > regional health authority) and note the discrepancy in the country detail page when material." },
        { heading: "Not a substitute for medical advice", body: "Nothing on Global Hanta Map should be interpreted as medical advice. If you suspect Hantavirus exposure or are experiencing symptoms — fever, muscle aches, fatigue, difficulty breathing — seek qualified medical attention immediately." },
        { heading: "Emergency contact guidance", body: "In a public health emergency, contact your country's national public health authority or local emergency services. Global Hanta Map is an information aggregator, not an emergency response service." },
        { heading: "Public health recommendations", body: "Specific public health recommendations (rodent control, ventilation of enclosed spaces, PPE while cleaning rural cabins, etc.) are summarized from official advisories. Always defer to the latest guidance from your local public health authority." },
        { heading: "AI-generated content disclosure", body: "Some textual summaries on this Service are generated by AI (Claude Sonnet 4.5) using only the verified outbreak figures and source names that we provide. AI summaries are clearly labelled and never fabricate numbers, names, or sources. Any errors should be reported to info@globalhantamap.com." },
        { heading: "No endorsement", body: "References to specific organizations, products, or commercial entities do not imply endorsement by Global Hanta Map." },
      ]}
    />
  );
}
